apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-portal-noticias
          livenessProbe:
            httpGet:
              path: / # página inicial (nesse caso)
              port: 80 # porta do container
            periodSeconds: 10 # periodicidade do teste
            failureThreshold: 3 # número de falhas antes de reiniciar o container 
            initialDelaySeconds: 20 # após 20 segundos de subir o container
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5 # número de falhas antes de retomar o envio de requisições ao container
            initialDelaySeconds: 3 # após início do POD e subida do container
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias