apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # ler e escrever apenas 1 POD por vez
  gcePersistentDisk:
    pdName: pv-disk
  storageClassName: standard